### ISSUE TITLE
No way to retrieve Sast.fdecl on function call

### ISSUE THREAD

**Issue by dannyech** [alexandramedway/odds#60]
When we analyze a function declaration, after we are done analyzing the actual declaration, the function becomes part of the Sast tree, and there is no way to retrieve the fdecl itself to check types on a function call.

An easy way to fix this would be to put all f_decls in a global Map called `FunctionMap`.

The keys for the map are the ss_ids of the functions, and the values are Sast.fdecl objects.

Does anybody see any issues with this approach? 

We wouldn't need to worry about scoping - i.e. a function being called in a scope it should not be able to be called in - because function names are themselves expressions (they're IDs), and resolving IDs always handles scope issues (it's the one place we would do this).

**Comment by akalicki** [comment]
We're solving this by adding functions as a variable type in the environment.
