### ISSUE TITLE
Reassigning parameters messes type constraining up.

### ISSUE THREAD

**Issue by dannyech** [alexandramedway/odds#63]
Say we have
```ocaml
do foo = (bar) -> do bar = bar + 2 do bar = "hi" return bar
```
then, the way we are doing constraining currently, we end up with `fun(string) -> string` when really we wanted `fun(num) -> string`. This issue happens when we reassign parameters to different types.

**Comment by dannyech** [comment]
Solution: 

```ocaml
    do function = (Unconst x) ->
        do z = int x + 2
        do x = string "hello, world"
        do x = concat(string x, "!")
        return whatever
        what is parameter type?

(x, false) -> x_0, string
(x, true) -> x_1, unconst
```
Key of varmap is tuple of raw name and is_parameter bool.

Each time we go down a scope level, if a param has same name as some 'global var' then get rid of global var, then keep going.

**Comment by dannyech** [comment]
x -> x_0 which is param
after x = "hello world"
x -> x_1

**Comment by akalicki** [comment]
Instead of keys, might have a `local` and `scope` section in env. When you go down a scope, obliterate all elements w/ param name in scope and add to local. Use a version in scope if it exists, otherwise use the local version. At end of function, use params in local to constrain function.

**Comment by dannyech** [comment]
That would work too, in fact, it's probably a better way of doing it :). Go with which ever one feels better to you.

**Comment by akalicki** [comment]
Fixed in the latest version of `constraint_system`
