### ISSUE TITLE
Reporting Compile-time errors to the user.

### ISSUE THREAD

**Issue by dannyech** [alexandramedway/odds#64]
Right now we are just calling `failwith message` if we hit an error in the analyzer.

Eventually we will want to catch errors in Scanner (this will be easy, and I plan on adding it soon) and Parser (harder, will also add). Since we are catching errors in the Scanner, Parser, and Analyzer, we should come up with a better, more scalable framework for reporting errors to the user. Here's my idea, feel free to add to it + critique:

We have three error types:
```ocaml
exception Illegal_Character_Sequence_Exception of string (* Errors in Scanner *)
exception Invalid_Something_Exception of string (* Errors in Parser *)
exception Semantic_Exception of string(* Errors in Analyzer *)
```

We would then catch and deal with these errors in the top level Odds.ml. The reason we have three different errors is that we might want to deal with Scanner, Parser, and Analyzer errors differently. We can use Ocaml's patten matching do detect which exception was raised:

```ocaml
try
( * do stuff here * ) 
with
  | Illegal_Character_Sequence_Exception(m) -> (* Report to user *)
  | Invalid_Something_Exception(m) -> (* Report to user in a different way *)
  | Semantic_Exception(m) -> (* Report to user in yet another way *)
```

**Comment by akalicki** [comment]
This looks good, but why would we want to catch the errors? They're all breaking in our compiler flow and should probably just result in program termination + a print to stderr (default exception behavior)

**Comment by dannyech** [comment]
We don't need to, you're right. I thought it might just be 1) organizationally better and 2) allow us to do more interesting things with the error reporting to the user

**Comment by dannyech** [comment]
also failwith appends this ugly "Fatal Error:" to the beginning of the error message

**Comment by dannyech** [comment]
also i think the only way to catch parse errors might be to have a try-with, but not 100% sure

**Comment by akalicki** [comment]
Yeah I like the idea of creating our own exceptions instead of `failwith`, but I think it will be sufficient to do 
```ocaml
raise Semantic_Exception("my_exception")
```
without the try catch block.

**Comment by dannyech** [comment]
Agreed! That way if we do choose to do something fancier down the line it will be easy to do so.

**Comment by dannyech** [comment]
Ahhh, ok, so as i'm testing it out, to get rid of the "Fatal Error" thing at the beginning, you need to catch, it... but we can add that in later

**Comment by akalicki** [comment]
Added in the latest version of `constraint_system`
